# Generated by Django 5.1.6 on 2025-03-07 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stage',
            name='duree',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='stage',
            name='renumeration',
            field=models.FloatField(default=0),
        ),
    ]
