# Generated by Django 5.1.6 on 2025-03-06 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stage', '0001_initial'),
        ('utilisateur', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateSoumission', models.DateField()),
                ('statut', models.CharField(max_length=50)),
                ('candidat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utilisateur.utilisateur')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stage.stage')),
            ],
        ),
    ]
